models/Post.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "post".
 *
 * @var array $images
 * @property integer $id
 * @property integer $user_id
 * @property integer $shows
 * @property string $title
 *
 * @property User $author
 */
class Post extends \yii\db\ActiveRecord
{
    const NO_IMAGE_FILE = 'no-image.png';
    public  $files;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'post';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title','user_id'], 'required'],
            [['title'], 'string', 'max' => 255],
            [['user_id','shows'], 'safe'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'user_id' => 'User ID',
            'shows' => 'Count View'
        ];
    }

    /**
     * @return array
     */
    public function getImages(){
       $images = array_map(function($entityt){
           return '/uploads/'.$entityt->path;},EntityImage::find()
           ->select('path')
           ->where([
               'entity' => Post::className(),
               'entity_id' => $this->id,
           ])->all());
       return !empty($images)? $images : [self::NO_IMAGE_FILE];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAuthor(){
        return $this->hasOne(User::className(),['id' => 'user_id']);
    }

    /**
     * @return string
     */
    public function getImage(){
        return $this->getImages()[0];
    }
}

controllers/PostController.php
<?php

namespace app\controllers;

use app\models\EntityImage;
use Yii;
use app\models\Post;
use app\models\PostSearch;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * PostController implements the CRUD actions for Post model.
 */
class PostController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'allow' => false,
                        'roles' => ['?']
                    ]
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Post models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PostSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Post model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
        $model->shows++;
        $model->save();

        return $this->render('view', [
            'model' => $model,
        ]);
    }

    public function actionTest(){
    }


    public function actionUpdate()
    {
        $id = Yii::$app->request->get('id');

        $model =  $id? $this->findModel($id) : new Post();
        $model->load(Yii::$app->request->post());
        if(Yii::$app->request->post()){
            $model->load(Yii::$app->request->post());
            $model->user_id = Yii::$app->user->id;
            $model->save();
            if(isset($_FILES )) {
                $entity = new EntityImage();
                $entity->entity = $model::className();
                $entity->entity_id = strval($model->id);

                $files = UploadedFile::getInstances($model, 'files');
                foreach ($files as $file) {
                    $ext = $file->extension;
                    $entity->path = Yii::$app->security->generateRandomString().".{$ext}";
                    if($entity->save()) {
                        $file->saveAs('uploads/' . $entity->path);
                    } else {
                        echo "<pre>"; var_dump($entity->getErrors()); die();
                    }
                }
            }
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Post model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Post model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Post the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Post::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\components\AuthHandler;
use app\models\EntityImage;
use app\models\Post;
use app\models\PostSearch;
use app\models\Profile;
use app\models\SignUpForm;
use app\models\User;
use Yii;
use yii\authclient\AuthAction;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use yii\web\UploadedFile;

class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
            'auth' => [
                'class' => AuthAction::class,
                'successCallback' => [$this, 'onAuthSuccess'],
            ],
        ];
    }

    public function onAuthSuccess($client)
    {

        (new AuthHandler($client))->handle();
    }


    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new PostSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }


    public function actionSignUp(){
        $form = new SignUpForm();

        if(!Yii::$app->user->isGuest){
            Yii::$app->user->logout();
        }

        if (Yii::$app->request->post('SignUpForm')) {
            $post = Yii::$app->request->post('SignUpForm');
            if($form->load(Yii::$app->request->post()) &&$form->validate()) {
                /**@var $user User*/
                $user = new User();
                $user->scenario = 'create';
                $user->email = $post['email'];
                $user->setPassword($post['password']);
                $user->name = $post['name'];

                if ($user->save()) {
                    $profile = new Profile();
                    $profile->user_id = $user->id;
                    $profile->city = $post['city'];
                    $profile->category = $post['category'];
                    $profile->text = $post['text'];
                    $profile->save();
                    Yii::$app->user->login($user, $post['rememberMe'] ? 3600 * 24 * 30 : 0);
                    return $this->goBack();
                } else {
                    echo "<pre>";
                    var_dump($user->getErrors());
                    die();
                }
            }

        }

        return $this->render('signUp', [
            'model' => $form,
        ]);
    }

    public function actionFileUpload(){
        $entity = new EntityImage();
        if(isset($_FILES )&& !empty($_POST['entity'])) {
            $entity->entity = $_POST['entity'];
            $files = UploadedFile::getInstancesByName('files');
            foreach ($files as $file) {
                $name = $file->name;
               $ext = end(explode(".", $name));
                $entity->path = Yii::$app->security->generateRandomString().".{$ext}";
                if($entity->save()) {
                    $file->saveAs('uploads/' . $entity->path);
                } else{
                    echo "<pre>"; var_dump($entity->getErrors()); die();
                }
            }
        }
    }

    public function actionTest(){
        $post = Post::findOne(2);
        echo "<pre>"; var_dump($post->getImages()); die();
    }
    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    public function actionPassword(){
        /* @var User $user */
        $user = Yii::$app->user->identity;
        $user->setPassword('123');
        $user->save();
        echo'saved';
    }
}

views/post/_form.php
<?php

use app\models\Post;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use kartik\widgets\FileInput;


/* @var $this yii\web\View */
/* @var $model app\models\Post */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="post-form">
    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>
    <div class="row">
    <?php

    foreach ($model->getImages() as $image) {
        echo Html::img(Url::to('/uploads/'.$image),['class' => 'prev_img']);
    }?>
    </div>
    <div class="row">
    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>
    <?php echo FileInput::widget([
        'model' => $model,
        'attribute' => 'files[]',
        'options'=>[
            'multiple'=>true,
            'resizeImages' => true,

        ],
        'resizeImages' => true,
        'pluginOptions' => [
            'resizeImages' => true
//            'uploadUrl' => Url::to(['/site/file-upload']),
//            'uploadExtraData' => [
//                'entity' => Post::className(),
//            ],
//            'maxFileCount' => 10
        ]
    ]); ?>
    </div>
    <div class="row">
        <div class="form-group" style="margin-top: 15px">
            <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/post/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\PostSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="post-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'title') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/post/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Post */

$this->title = 'Create Post';
$this->params['breadcrumbs'][] = ['label' => 'Posts', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="post-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/post/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\PostSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Posts';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="post-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Post', ['update'], ['class' => 'btn btn-success']) ?>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            'id',
            [
                'attribute' => 'image',
                'value' => function($data){
                    $img ='';
                    foreach ($data->getImages() as $image){
                      $img.= Html::img($image,['style' => 'height:100px;width:100px;']);
                    }
                    return $img;
                },
                'label' => 'images',
                'format' => 'html'
            ],
            'title',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

views/post/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Post */

$this->title = 'Update Post: ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Posts', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="post-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/post/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Post */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Posts', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="post-view">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'title',
        ],
    ]) ?>

    <?php   foreach ($model->getImages() as $image) {
        echo Html::img($image,['class' => 'prev_img_view']);
    } ?>

</div>