controllers/PostController.php
<?php

namespace app\controllers;

use app\models\EntityImage;
use Yii;
use app\models\Post;
use app\models\PostSearch;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * PostController implements the CRUD actions for Post model.
 */
class PostController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'allow' => false,
                        'roles' => ['?']
                    ]
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Post models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PostSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Post model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
        $model->shows++;
        $model->save();

        return $this->render('view', [
            'model' => $model,
        ]);
    }

    public function actionTest(){
    }


    public function actionUpdate()
    {
        $id = Yii::$app->request->get('id');

        $model =  $id? $this->findModel($id) : new Post();
        $model->load(Yii::$app->request->post());
        if(Yii::$app->request->post()){
            $model->load(Yii::$app->request->post());
            $model->user_id = Yii::$app->user->id;
            $model->save();
            if(isset($_FILES )) {
                $entity = new EntityImage();
                $entity->entity = $model::className();
                $entity->entity_id = strval($model->id);

                $files = UploadedFile::getInstances($model, 'files');
                foreach ($files as $file) {
                    $ext = $file->extension;
                    $entity->path = Yii::$app->security->generateRandomString().".{$ext}";
                    if($entity->save()) {
                        $file->saveAs('uploads/' . $entity->path);
                    } else {
                        echo "<pre>"; var_dump($entity->getErrors()); die();
                    }
                }
            }
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Post model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Post model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Post the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Post::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\components\AuthHandler;
use app\models\EntityImage;
use app\models\Post;
use app\models\PostSearch;
use app\models\Profile;
use app\models\SignUpForm;
use app\models\User;
use Yii;
use yii\authclient\AuthAction;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use yii\web\UploadedFile;

class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
            'auth' => [
                'class' => AuthAction::class,
                'successCallback' => [$this, 'onAuthSuccess'],
            ],
        ];
    }

    public function onAuthSuccess($client)
    {

        (new AuthHandler($client))->handle();
    }


    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new PostSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }


    public function actionSignUp(){
        $form = new SignUpForm();

        if(!Yii::$app->user->isGuest){
            Yii::$app->user->logout();
        }

        if (Yii::$app->request->post('SignUpForm')) {
            $post = Yii::$app->request->post('SignUpForm');
            if($form->load(Yii::$app->request->post()) &&$form->validate()) {
                /**@var $user User*/
                $user = new User();
                $user->scenario = 'create';
                $user->email = $post['email'];
                $user->setPassword($post['password']);
                $user->name = $post['name'];

                if ($user->save()) {
                    $profile = new Profile();
                    $profile->user_id = $user->id;
                    $profile->city = $post['city'];
                    $profile->category = $post['category'];
                    $profile->text = $post['text'];
                    $profile->save();
                    Yii::$app->user->login($user, $post['rememberMe'] ? 3600 * 24 * 30 : 0);
                    return $this->goBack();
                } else {
                    echo "<pre>";
                    var_dump($user->getErrors());
                    die();
                }
            }

        }

        return $this->render('signUp', [
            'model' => $form,
        ]);
    }

    public function actionFileUpload(){
        $entity = new EntityImage();
        if(isset($_FILES )&& !empty($_POST['entity'])) {
            $entity->entity = $_POST['entity'];
            $files = UploadedFile::getInstancesByName('files');
            foreach ($files as $file) {
                $name = $file->name;
               $ext = end(explode(".", $name));
                $entity->path = Yii::$app->security->generateRandomString().".{$ext}";
                if($entity->save()) {
                    $file->saveAs('uploads/' . $entity->path);
                } else{
                    echo "<pre>"; var_dump($entity->getErrors()); die();
                }
            }
        }
    }

    public function actionTest(){
        $post = Post::findOne(2);
        echo "<pre>"; var_dump($post->getImages()); die();
    }
    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    public function actionPassword(){
        /* @var User $user */
        $user = Yii::$app->user->identity;
        $user->setPassword('123');
        $user->save();
        echo'saved';
    }
}

views/site/_post_item.php
<?php
/**
 * @var $model Post
 */
use app\models\Post;
use yii\bootstrap\Html;
?>
<div class="post">
    <div class="white_block">
        <a href="<?= \yii\helpers\Url::to(['post/view','id' => $model->id])?>">
            <img src="<?= $model->getImages()[0] ?>" height="250" width="200" class="cover">
        </a>
        <div class="white_block post_icons_block" >
            <span class="icon">
                <i class="fa fa-eye" aria-hidden="true"></i><?= $model->shows ?>
            </span>
            <span class="icon">
            <i class="fa fa-heart" aria-hidden="true"></i><?= rand(13,1000) ?>
                </span>
            <span class="icon">
                <i class="fa fa-comment" aria-hidden="true"></i><?= rand(13,1000) ?>
            </span>
        </div>
    </div>
    <div class="user">
        <table>
            <tr>
                <td>
                    <?= Html::img($model->author->getPhoto(),['class' => 'user_icon']) ?>
                </td>
                <td>
                    <?= $model->author->name ?>
                </td>
            </tr>
        </table>
    </div>
</div>

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/* @var $this yii\web\View
 * @var $dataProvider \yii\data\ActiveDataProvider
 */

use yii\widgets\ListView;

$this->title = 'My Yii Application';
?>
<div class="site-index">
        <div class="row">
            <?=
                ListView::widget([
                    'dataProvider' => $dataProvider,
                    'options' => [
                        'tag' => 'div',
                        'class' => 'list-wrapper',
                        'id' => 'list-wrapper',

                    ],
                    'itemOptions' => [
                        'class' => 'post_container'
                    ],
                    'itemView' => function ($model, $key, $index, $widget) {
                        return $this->render('_post_item', ['model' => $model]);
                    },
                    'layout' => "{items}\n{summary}\n{pager}\n",
                ]);
            ?>
        </div>

</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'email')->textInput() ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>
        <?= Html::a('Registration', \yii\helpers\Url::to('sign-up'))?>

        <?= yii\authclient\widgets\AuthChoice::widget([
            'baseAuthUrl' => ['site/auth'],
            'popupMode' =>false,
        ]) ?>
        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>



    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>

views/site/signUp.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = Yii::$app->user->isGuest? 'Sign Up' : 'Update Account Data';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to create account:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'signUp-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

    <?= $form->field($model, 'name')->textInput() ?>
    <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>
    <?= $form->field($model, 'password')->passwordInput() ?>
    <?= $form->field($model, 'city')->textInput()?>
    <?= $form->field($model, 'category')->textInput() ?>
    <?= $form->field($model, 'text')->textarea() ?>
    <?= $form->field($model, 'rememberMe')->checkbox([
        'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
    ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton( Yii::$app->user->isGuest? 'Create' : 'Update', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

</div>